export const INDUSTRY = [
  "Accounting - Finance",
  "Advertising",
  "Agriculture",
  "Airline - Aviation",
  "Architecture - Building",
  "Art - Photography - Journalism",
  "Automotive - Motor Vehicles - Parts",
  "Banking - Financial Service",
  "Biotechnology",
  "Broadcasting- Radio - TV",
  "Building Material",
  "Chemical",
  "Construction",
  "Computer Hardware",
  "Computer Software",
  "Consulting",
  "Consumer Products",
  "Credit - Loan - Collections",
  "Defense - Aerospace",
  "Education - Teaching - Administration",
  "Electronics",
  "Employment- Recruiting - Staffing",
  "Energy - Utilities - Gas - Electric",
  "Entertainment",
  "Environmental",
  "Exercise - Fitness",
  "Fashion - Apparel- Textile",
  "Food",
  "Funeral - Cemetery",
  "Government - Civil Service",
  "Healthcare - Health Services",
  "Homebuilding",
  "Hospitality",
  "Hotel - Resort",
  "HVAC",
  "Import - Export",
  "Industrial",
  "Insurance",
  "Internet- ECommerce",
  "Landscaping",
  "Law Enforcement",
  "Legal",
  "Library Science",
  "Managed Car",
  "Manufacturing",
  "Medical Equipment",
  "Merchandising",
  "Military",
  "Mortgage",
  "Newspaper",
  "Not for Profit - Charitable",
  "Office Supplies - Equipment",
  "Oil Refining - Petroleum -Drilling",
  "Other Great Industries",
  "Packaging",
  "Pharmaceutical",
  "Printing - Publishing",
  "Public Relation",
  "Real Estate - Property Mgt",
  "Restaurant",
  "Retail",
  "Recreation",
  "Sales - Marketing",
  "Security",
  "Securities",
  "Semiconductor",
  "Social Services",
  "Telecommunications",
  "Training",
  "Transportation",
  "Travel",
  "Wireless",
];

export const JOBS = [
  "Account Executive",
  "Account Manager",
  "Account Representative",
  "Accountant",
  "Accounting Assistant",
  "Accounting Clerk",
  "Activities Assistant",
  "Activities Coordinator",
  "Activities Director",
  "Activity Director",
  "Adjunct Faculty",
  "Adjunct Instructor",
  "Adjunct Professor",
  "Administrative Assistant",
  "Admissions Advisor",
  "Aerospace Engineer",
  "Aircraft Mechanic",
  "Android Developer",
  "Appointment Setter",
  "Architect",
  "Armed Officer",
  "Armed Security Officer",
  "Art Director",
  "Asset Protection Manager",
  "Assistant Controller",
  "Assistant Store Manager",
  "Auditor",
  "Automotive Service Advisor",
  "Automotive Service Manager",
  "Automotive Technician",
  "Avionics Technician",
  "Background Investigator",
  "Bank Teller",
  "Banquet Server",
  "Barista",
  "Bartender",
  "Behavior Specialist",
  "Biochemist",
  "Biological Scientist",
  "Biomedical Equipment Technician",
  "Brand Ambassador",
  "Budget Analyst",
  "Build Engineer",
  "Building Inspector",
  "Bus Driver",
  "Business Analyst",
  "Business Development Manager",
  "Busser",
  "Cable Technician",
  "Call Center Manager",
  "Call Center Supervisor",
  "Career Counselor",
  "Caregiver",
  "Caretaker",
  "Case Manager",
  "Cashier",
  "Catering Manager",
  "Certified Medical Assistant",
  "Certified Medication Aide",
  "Certified Nursing Assistant",
  "Certified Occupational Therapy Assistant",
  "Chaplain",
  "Chauffeur",
  "Chef",
  "Chemical Engineer",
  "Chemical Operator",
  "Chemist",
  "Civil Engineer",
  "Claims Adjuster",
  "Clerk",
  "Clinical Assistant",
  "Clinical Research Associate",
  "Clinical Social Worker",
  "Clinician",
  "CNC Machinist",
  "Collector",
  "Communications Manager",
  "Communications Specialist",
  "Compensation Analyst",
  "Concierge",
  "Concrete Foreman",
  "Construction Engineer",
  "Construction Estimator",
  "Construction Inspector",
  "Construction Manager",
  "Construction Supervisor",
  "Consultant",
  "Content Writer",
  "Contract Attorney",
  "Controller",
  "Controls Engineer",
  "Cook",
  "Corporate Attorney",
  "Corporate Counsel",
  "Corporate Paralegal",
  "Corporate Trainer",
  "Correctional Officer",
  "Cosmetologist",
  "Cosmetology Instructor",
  "Cost Accountant",
  "Courier",
  "Crane Operator",
  "Creative Director",
  "Credit Analyst",
  "Criminal Justice Instructor",
  "Customer Service Manager",
  "Customer Service Representative",
  "Customer Service Supervisor",
  "Data Analyst",
  "Data Entry Clerk",
  "Database Administrator",
  "Delivery Driver",
  "Dental Hygienist",
  "Design Engineer",
  "Detention Officer",
  "Diesel Mechanic",
  "Diesel Technician",
  "Dietary Aide",
  "Direct Support Professional",
  "Director of Education",
  "Director of Nursing",
  "Director of Operations",
  "Dishwasher",
  "Dispatcher",
  "Distribution Manager",
  "Distribution Supervisor",
  "Dock Worker",
  "Doorman",
  "Driller",
  "Driver Helper",
  "Driver/Guard",
  "Economist",
  "Editor",
  "Editorial Assistant",
  "Electrical Apprentice",
  "Electrical Engineer",
  "Electrical Helper",
  "Electrical Superintendent",
  "Electrician",
  "Electronic Assembler",
  "Electronic Technician",
  "Electronics Engineer",
  "Electronics Technician",
  "Elementary School Teacher",
  "Embalmer",
  "Engineering Technician",
  "English Instructor",
  "English Teacher",
  "Environmental Engineer",
  "Environmental Scientist",
  "Environmental Services Director",
  "Environmental Services Manager",
  "Environmental Services Supervisor",
  "Environmental Services Worker",
  "Environmental Specialist",
  "Environmental Technician",
  "Equipment Operator",
  "Equipment Technician",
  "Esthetician",
  "Estimator",
  "ETL Developer",
  "Event Coordinator",
  "Executive Administrative Assistant",
  "Executive Assistant",
  "Executive Director",
  "Facility Security Officer",
  "Farm Manager",
  "Field Engineer",
  "Field Representative",
  "Field Service Engineer",
  "Field Service Technician",
  "Field Technician",
  "File Clerk",
  "Finance Manager",
  "Financial Advisor",
  "Financial Analyst",
  "Fire Chief",
  "Fire Fighter",
  "Fire Inspector",
  "Fitness Instructor",
  "Fitness Manager",
  "Fitness Specialist",
  "Fitness Trainer",
  "Floor Technician",
  "Food Inspector",
  "Food Scientist",
  "Food Service Manager",
  "Food Service Supervisor",
  "Food Technologist",
  "Foreclosure Paralegal",
  "Foreman",
  "Forklift Driver",
  "Forklift Operator",
  "Fraud Investigator",
  "General Cleaner",
  "General Counsel",
  "General Laborer",
  "General Manager",
  "Graphic Artist",
  "Graphic Designer",
  "Greeter",
  "Groomer",
  "Grounds Keeper",
  "Grounds Manager",
  "Hair Stylist",
  "Handyman",
  "Health Care Assistant",
  "Healthcare Attorney",
  "Home Health Aide",
  "Home Health Nurse",
  "Hospice Aide",
  "Housekeeper",
  "Housekeeping Manager",
  "Housekeeping Supervisor",
  "Houseperson",
  "Human Resources Manager",
  "Human Resources Assistant",
  "Illustrator",
  "Immigration Attorney",
  "Immigration Paralegal",
  "In-House Counsel",
  "Industrial Electrician",
  "Industrial Engineer",
  "Informatica Developer",
  "Inside Sales Representative",
  "Installation Technician",
  "Instructional Designer",
  "Instructor",
  "Instrumentation Technician",
  "Insurance Adjuster",
  "Insurance Sales Agent",
  "Intellectual Property Attorney",
  "Intelligence Analyst",
  "Interior Designer",
  "Interpreter",
  "Investment Analyst",
  "IT Manager",
  "Janitorial Supervisor",
  "Java Developer",
  "Job Coach",
  "Journalist",
  "Journeyman Electrician",
  "Kindergarten Teacher",
  "Kitchen Supervisor",
  "Lab Technician",
  "Laboratory Supervisor",
  "Laboratory Technician",
  "Laborer",
  "Landscape Foreman",
  "Landscape Laborer",
  "Law Clerk",
  "Law Enforcement Officer",
  "Lawyer",
  "Leasing Agent",
  "Leasing Consultant",
  "Legal Analyst",
  "Legal Assistant",
  "Legal Clerk",
  "Legal Counsel",
  "Legal Secretary",
  "Librarian",
  "Lifeguard",
  "Line Cook",
  "Litigation Attorney",
  "Litigation Paralegal",
  "Loader",
  "Loan Officer",
  "Loan Processor",
  "Logistics Manager",
  "Loss Prevention Associate",
  "Loss Prevention Manager",
  "Machine Operator",
  "Machinist",
  "Mail Clerk",
  "Mainframe Developer",
  "Maintenance Manager",
  "Maintenance Mechanic",
  "Maintenance Planner",
  "Maintenance Technician",
  "Maintenance Worker",
  "Manual Machinist",
  "Manufacturing Engineer",
  "Manufacturing Manager",
  "Manufacturing Supervisor",
  "Marketing Assistant",
  "Marketing Coordinator",
  "Marketing Manager",
  "Marketing Specialist",
  "Massage Therapist",
  "Materials Engineer",
  "Materials Scientist",
  "Mechanical Assembler",
  "Mechanical Engineer",
  "Medical Assistant",
  "Medical Assistant Instructor",
  "Medical Biller",
  "Medical Coder",
  "Medical Receptionist",
  "Medical Sales Representative",
  "Medical Transcriptionist",
  "Medical Writer",
  "Mental Health Professional",
  "Mental Health Technician",
  "Mental Health Worker",
  "Merchandiser",
  "Microbiologist",
  "Mortgage Underwriter",
  ".Net Developer",
  "Nanny",
  "Network Engineer",
  "Nurse Aide",
  "Nurse Assistant",
  "Nurse Manager",
  "Nurse Practitioner",
  "Nursing Instructor",
  "Occupational Therapist",
  "Occupational Therapy Assistant",
  "Office Assistant",
  "Office Manager",
  "Operations Manager",
  "Operations Supervisor",
  "Oracle Developer",
  "Orthodontic Assistant",
  "Package Handler",
  "Packaging Engineer",
  "Packer",
  "Paralegal",
  "Paramedic",
  "Paraprofessional",
  "Parts Manager",
  "Patent Attorney",
  "Patient Care Assistant",
  "Patrol Officer",
  "PC Technician",
  "Personal Assistant",
  "Personal Banker",
  "Personal Care Aide",
  "Personal Care Assistant",
  "Personal Injury Paralegal",
  "Personal Trainer",
  "Pest Control Technician",
  "Pet Groomer",
  "Pharmacist",
  "Phlebotomy Technician",
  "Photographer",
  "Physical Education Teacher",
  "Physical Therapist Assistant",
  "Physical Therapy Aide",
  "Physical Therapy Technician",
  "Physician Assistant",
  "Plant Controller",
  "Plant Manager",
  "Plumber",
  "Police Chief",
  "Police Officer",
  "Porter",
  "Preschool Teacher",
  "Press Operator",
  "Process Engineer",
  "Process Operator",
  "Producer",
  "Product Engineer",
  "Product Manager",
  "Production Artist",
  "Production Manager",
  "Production Supervisor",
  "Production Worker",
  "Professor",
  "Program Manager",
  "Programmer",
  "Project Analyst",
  "Project Coordinator",
  "Project Engineer",
  "Project Manager",
  "Proofreader",
  "Property Accountant",
  "Property Manager",
  "Psychologist",
  "Psychology Instructor",
  "Public Safety Officer",
  "Purchasing Manager",
  "Quality Assurance Analyst",
  "Quality Control Inspector",
  "Quality Engineer",
  "Quality Inspector",
  "Quality Supervisor",
  "Quality Technician",
  "Real Estate Agent",
  "Real Estate Attorney",
  "Real Estate Paralegal",
  "Receptionist",
  "Recreation Assistant",
  "Recreation Director",
  "Recreation Specialist",
  "Recruiter",
  "Registered Dental Assistant",
  "Registered Nurse",
  "Repair Technician",
  "Research Analyst",
  "Research Associate",
  "Resident Assistant",
  "Respiratory Therapist",
  "Restaurant Supervisor",
  "Retail Merchandiser",
  "Retail Sales Associate",
  "Roofer",
  "Room Attendant",
  "Route Sales Driver",
  "Safety Manager",
  "Sales Associate",
  "Sales Consultant",
  "Sales Coordinator",
  "Sales Director",
  "Sales Engineer",
  "Sales Manager",
  "Sales Representative",
  "Salon Manager",
  "Sanitation Worker",
  "School Nurse",
  "Science Teacher",
  "Secretary",
  "Security Director",
  "Security Guard",
  "Security Investigator",
  "Security Manager",
  "Security Officer",
  "Security Specialist",
  "Security Supervisor",
  "Server",
  "Service Technician",
  "SharePoint Developer",
  "Sheriff",
  "Shift Manager",
  "Shipping Manager",
  "Shipping Supervisor",
  "Shop Manager",
  "Social Studies Teacher",
  "Software Engineer",
  "Sous Chef",
  "Spanish Teacher",
  "SQL Developer",
  "Staff Accountant",
  "Staff Attorney",
  "Staffing Coordinator",
  "Store Manager",
  "Structural Engineer",
  "Stylist",
  "Substance Abuse Counselor",
  "Substitute Teacher",
  "Superintendent",
  "Surgical Technician",
  "Systems Administrator",
  "Systems Analyst",
  "Systems Engineer",
  "Tax Accountant",
  "Tax Attorney",
  "Teacher",
  "Teacher Aide",
  "Teacher Assistant",
  "Teaching Assistant",
  "Technical Writer",
  "Telecommunications Technician",
  "Teller",
  "Terminal Manager",
  "Therapeutic Staff Support",
  "Title Closer",
  "Title Examiner",
  "Title Processor",
  "Tower Climber",
  "Trademark Attorney",
  "Trader",
  "Trailer Mechanic",
  "Training Manager",
  "Transcriptionist",
  "Translator",
  "Transportation Manager",
  "Transportation Security Officer",
  "Transportation Supervisor",
  "Travel Agent",
  "Travel Consultant",
  "Tree Trimmer",
  "Truck Driver",
  "Tutor",
  "Ultrasonographer",
  "Ultrasound Technician",
  "Ultrasound Technologist",
  "UMTS Engineer",
  "Underground Miner",
  "Underwriter",
  "Underwriting Assistant",
  "Underwriting Director",
  "Underwriting Manager",
  "Union Organizer",
  "Union Representative",
  "Unit Clerk",
  "Unit Coordinator",
  "Unit Manager",
  "Unit Operator",
  "Unit Secretary",
  "University Administrator",
  "University Dean",
  "University Librarian",
  "University President",
  "University Professor",
  "Unix Administrator",
  "Unix Systems Administrator",
  "Unloader",
  "Upholsterer",
  "Upholsterers",
  "UPS Driver",
  "Urban And Regional Planners",
  "Urban Designer",
  "Urban Planner",
  "Urban Planning Professor",
  "Urologist",
  "Usability Engineer",
  "Usability Specialist",
  "User Experience Designer",
  "User Experience Director",
  "User Interface Designer",
  "Usher",
  "Utilities Manager",
  "Utilities Operator",
  "Utility Engineer",
  "Utility Locator",
  "Utility Operator",
  "Utility Technician",
  "Utility Worker",
  "Valet",
  "Validation Engineer",
  "Van Driver",
  "Vascular Surgeon",
  "Vascular Technician",
  "Veterinarian",
  "Vice President",
  "Vice Principal",
  "Video Coordinator",
  "Video Editor",
  "Video Game Designer",
  "Video Game Developer",
  "Video Game Tester",
  "Video Producer",
  "Video Technician",
  "Videographer",
  "Visual Artist",
  "Visual Designer",
  "Visual Merchandiser",
  "Warehouse Associate",
  "Warehouse Driver",
  "Warehouse Lead",
  "Warehouse Manager",
  "Warehouse Supervisor",
  "Warehouse Worker",
  "Washer",
  "Web Developer",
  "Welder",
  "Welding Engineer",
  "Welding Supervisor",
  "Wellness Coordinator",
  "Windows Administrator",
  "Writer",
  "X Ray Technician",
  "Yard Laborer",
  "Yard Manager",
  "Yard Spotter",
  "Yard Supervisor",
  "Yard Worker",
  "Yardman",
  "Yoga Instructor",
  "Young Adult Librarian",
  "Youth Advocate",
  "Youth Coordinator",
  "Youth Minister",
  "Youth Ministry Director",
  "Youth Pastor",
  "Youth Program Director",
  "Youth Services Librarian",
  "Youth Services Specialist",
  "Youth Teacher",
  "Zone Manager",
  "Zoning Administrator",
  "Zoning Technician",
  "Zookeeper",
];

export const INTERVIEW_DURATION = 10;

export const INCREASE_DURATION = 5;

export const CHAT_LIMIT = 4;

export const VIEWABLE_CHAT = 3;

export const DEMO_USER_EMAIL = "usman.ghani720+michael@gmail.com";

export const DEMO_SEEKER_ONE_EMAIL = "usman.ghani720+roger@gmail.com";

export const DEMO_SEEKER_TWO_EMAIL = "usman.ghani720+nadal@gmail.com";

export const DEMO_SEEKER_THREE_EMAIL = "usman.ghani720+murray@gmail.com";

export const DEMO_SEEKER_FOUR_EMAIL = "usman.ghani720+sampres@gmail.com";

export const DEMO_RECRUITER_EMAIL = "usman.ghani720+dummy_michael@gmail.com";

export const DEMO_EMPLOYER_WITH_NO_BOOTH_MEDIA = "talalshahid20+1231@gmail.com";

export const DEMO_EMPLOYER_LATEST = "talalshahid20+2221@gmail.com";

export const DEMO_EMPLOYER_WITH_ONE_BOOTH_MEDIA =
  "talalshahid20+3321@gmail.com";

export const DEMO_EVENT = 325;
